# Generated by Django 3.0.6 on 2020-05-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200512_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
