# Generated by Django 3.0.6 on 2020-05-15 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_message_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='fromTo',
        ),
    ]
