# Generated by Django 3.0.6 on 2020-05-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_message_fromto'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
    ]
