# Generated by Django 3.0.6 on 2020-05-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tag',
        ),
    ]
