# Generated by Django 3.0.6 on 2020-05-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_message_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromTo',
            field=models.DecimalField(decimal_places=0, help_text='1 => a->b || 2=> b->a', max_digits=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(),
        ),
    ]
